name: WarpBuild Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - run: |
          export DOCKER_HOST=${{ secrets.WARPDEV_DOCKER_HOST }}
          docker build -t mastodon . \
            --builld-arg MASTODON_VERSION_PRERELEASE=warpbench \
            --builld-arg MASTODON_VERSION_METADATA=warpbench \
            --builld-arg SOURCE_COMMIT=${{ github.sha }}
