name: WarpBuild Docker Build

on:
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - run: |
          export DOCKER_HOST=${{ secrets.WARPDEV_DOCKER_HOST }}
          docker buildx build -t mastodon . \
            --build-arg MASTODON_VERSION_PRERELEASE=warpbench \
            --build-arg MASTODON_VERSION_METADATA=warpbench \
            --build-arg SOURCE_COMMIT=${{ github.sha }}
